### ISSUE TITLE
[Bug] Heroku COLLECTSTATIC

### ISSUE THREAD

**Issue by 4923** [VENCLFIT/watch-your-neck#1]
# :bug: Push rejected, failed to compile Python app. 

<details>
<summary>log</summary>

```
-----> Building on the Heroku-20 stack
-----> Determining which buildpack to use for this app
-----> Python app detected
-----> No Python version was specified. Using the buildpack default: python-3.10.4
       To use a different version, see: https://devcenter.heroku.com/articles/python-runtimes
-----> Installing python-3.10.4
-----> Installing pip 22.0.4, setuptools 60.10.0 and wheel 0.37.1
-----> Installing SQLite3
-----> Installing requirements with pip
       Collecting asgiref==3.5.2
         Downloading asgiref-3.5.2-py3-none-any.whl (22 kB)
       Collecting Django==3.2.13
         Downloading Django-3.2.13-py3-none-any.whl (7.9 MB)
       Collecting django-environ==0.8.1
         Downloading django_environ-0.8.1-py2.py3-none-any.whl (17 kB)
       Collecting django-pwa==1.0.10
         Downloading django_pwa-1.0.10-py3-none-any.whl (456 kB)
       Collecting pytz==2022.1
         Downloading pytz-2022.1-py2.py3-none-any.whl (503 kB)
       Collecting setuptools==47.1.0
         Downloading setuptools-47.1.0-py3-none-any.whl (583 kB)
       Collecting sqlparse==0.4.2
         Downloading sqlparse-0.4.2-py3-none-any.whl (42 kB)
       Collecting typing_extensions==4.2.0
         Downloading typing_extensions-4.2.0-py3-none-any.whl (24 kB)
       Installing collected packages: pytz, typing_extensions, sqlparse, setuptools, django-environ, asgiref, Django, django-pwa
         Attempting uninstall: setuptools
           Found existing installation: setuptools 60.10.0
           Uninstalling setuptools-60.10.0:
             Successfully uninstalled setuptools-60.10.0
       Successfully installed Django-3.2.13 asgiref-3.5.2 django-environ-0.8.1 django-pwa-1.0.10 pytz-2022.1 setuptools-47.1.0 sqlparse-0.4.2 typing_extensions-4.2.0
-----> $ python project/manage.py collectstatic --noinput
       Traceback (most recent call last):
         File "/app/.heroku/python/lib/python3.10/site-packages/environ/environ.py", line 367, in get_value
           value = self.ENVIRON[var]
         File "/app/.heroku/python/lib/python3.10/os.py", line 679, in __getitem__
           raise KeyError(key) from None
       KeyError: 'SECRET_KEY'
       During handling of the above exception, another exception occurred:
       Traceback (most recent call last):
         File "/tmp/build_deb7fd35/project/manage.py", line 22, in <module>
           main()
         File "/tmp/build_deb7fd35/project/manage.py", line 18, in main
           execute_from_command_line(sys.argv)
         File "/app/.heroku/python/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
           utility.execute()
         File "/app/.heroku/python/lib/python3.10/site-packages/django/core/management/__init__.py", line 413, in execute
           self.fetch_command(subcommand).run_from_argv(self.argv)
         File "/app/.heroku/python/lib/python3.10/site-packages/django/core/management/__init__.py", line 244, in fetch_command
           settings.INSTALLED_APPS
         File "/app/.heroku/python/lib/python3.10/site-packages/django/conf/__init__.py", line 82, in __getattr__
           self._setup(name)
         File "/app/.heroku/python/lib/python3.10/site-packages/django/conf/__init__.py", line 69, in _setup
           self._wrapped = Settings(settings_module)
         File "/app/.heroku/python/lib/python3.10/site-packages/django/conf/__init__.py", line 170, in __init__
           mod = importlib.import_module(self.SETTINGS_MODULE)
         File "/app/.heroku/python/lib/python3.10/importlib/__init__.py", line 126, in import_module
           return _bootstrap._gcd_import(name[level:], package, level)
         File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
         File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
         File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
         File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
         File "<frozen importlib._bootstrap_external>", line 883, in exec_module
         File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
         File "/tmp/build_deb7fd35/project/project/settings.py", line 32, in <module>
           SECRET_KEY = env('SECRET_KEY')
         File "/app/.heroku/python/lib/python3.10/site-packages/environ/environ.py", line 175, in __call__
           return self.get_value(
         File "/app/.heroku/python/lib/python3.10/site-packages/environ/environ.py", line 371, in get_value
           raise ImproperlyConfigured(error_msg)
       django.core.exceptions.ImproperlyConfigured: Set the SECRET_KEY environment variable
 !     Error while running '$ python project/manage.py collectstatic --noinput'.
       See traceback above for details.
       You may need to update application code to resolve this error.
       Or, you can disable collectstatic for this application:
          $ heroku config:set DISABLE_COLLECTSTATIC=1
       https://devcenter.heroku.com/articles/django-assets
 !     Push rejected, failed to compile Python app.
 !     Push failed
```

</details>

## 확인방법
`.env` 설정 후 heroku에서 main으로 배포 (권한 부여 필)

## 추정 원인
collect static을 disable하라는데 왜...? 이미 로컬에서 에러나는 부분을 잡았는데도 웹에서 문제 생기는 이유를 알 수 없다.

- [x] static 위치 확인
- [x] settings.py 에서 STATIC_ROOT 확인, 경로 확인
- [x] 로컬에서 `python manage.py collectstatic` 로 static 수집 완료

- [참고 stackoverflow](https://stackoverflow.com/questions/36665889/collectstatic-error-while-deploying-django-app-to-heroku)

## 기타
헤로쿠와의 악연을 끝내고 싶다... 추후 디버깅

**Comment by 4923** [comment]
`heroku config:set DISABLE_COLLECTSTATIC=1` 명령 실행 시 추가 옵션을 붙이라는 경고 발생

<img width="367" alt="image" src="https://user-images.githubusercontent.com/60145951/172029907-766cb20b-8ec0-4dbc-890c-e3b0cc4d3714.png">

정책상의 변경은 없는지, 업데이트 된 바는 없는지 확인 필요.
- 현재 장고 최신버전 4.0.1 / 내 장고 왜... 2.2? / 참고한 stackoverflow 버전 1.10

**Comment by 4923** [comment]
## whitenoise
공식문서 하단에 안내된 whitenoise를 설치했으나 결과는 같다. 97ddfe53b3c6eed91e13d4ecc729d369752c3a60
- [참고](https://velog.io/@han0707/django-heroku-error)

그런데 에러코드 하단에 느낌표가 찍혀있길래 하단만 봤더니 위를 보니 뭔가 좀 다르다

**Comment by 4923** [comment]
<details>
<summary>runserver Trouble shooting</summary>

```
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Users/a4923/.pyenv/versions/3.7.13/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/Users/a4923/.pyenv/versions/3.7.13/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/a4923/.pyenv/versions/django-envs/lib/python3.7/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/a4923/.pyenv/versions/django-envs/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 138, in inner_run
    handler = self.get_handler(*args, **options)
  File "/Users/a4923/.pyenv/versions/django-envs/lib/python3.7/site-packages/django/contrib/staticfiles/management/commands/runserver.py", line 27, in get_handler
    handler = super().get_handler(*args, **options)
  File "/Users/a4923/.pyenv/versions/django-envs/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 65, in get_handler
    return get_internal_wsgi_application()
  File "/Users/a4923/.pyenv/versions/django-envs/lib/python3.7/site-packages/django/core/servers/basehttp.py", line 45, in get_internal_wsgi_application
    return import_string(app_path)
  File "/Users/a4923/.pyenv/versions/django-envs/lib/python3.7/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/Users/a4923/.pyenv/versions/3.7.13/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/a4923/Desktop/repositories/watch-your-neck/project/project/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/Users/a4923/.pyenv/versions/django-envs/lib/python3.7/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    return WSGIHandler()
  File "/Users/a4923/.pyenv/versions/django-envs/lib/python3.7/site-packages/django/core/handlers/wsgi.py", line 127, in __init__
    self.load_middleware()
  File "/Users/a4923/.pyenv/versions/django-envs/lib/python3.7/site-packages/django/core/handlers/base.py", line 58, in load_middleware
    mw_instance = middleware(adapted_handler)
  File "/Users/a4923/.pyenv/versions/django-envs/lib/python3.7/site-packages/whitenoise/storage.py", line 131, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/a4923/.pyenv/versions/django-envs/lib/python3.7/site-packages/django/contrib/staticfiles/storage.py", line 373, in __init__
    self.hashed_files = self.load_manifest()
  File "/Users/a4923/.pyenv/versions/django-envs/lib/python3.7/site-packages/django/contrib/staticfiles/storage.py", line 383, in load_manifest
    content = self.read_manifest()
  File "/Users/a4923/.pyenv/versions/django-envs/lib/python3.7/site-packages/django/contrib/staticfiles/storage.py", line 377, in read_manifest
    with self.open(self.manifest_name) as manifest:
  File "/Users/a4923/.pyenv/versions/django-envs/lib/python3.7/site-packages/django/core/files/storage.py", line 38, in open
    return self._open(name, mode)
  File "/Users/a4923/.pyenv/versions/django-envs/lib/python3.7/site-packages/django/core/files/storage.py", line 243, in _open
    return File(open(self.path(name), mode))
  File "/Users/a4923/.pyenv/versions/django-envs/lib/python3.7/site-packages/django/contrib/staticfiles/storage.py", line 37, in path
    if not self.location:
  File "/Users/a4923/.pyenv/versions/django-envs/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/a4923/.pyenv/versions/django-envs/lib/python3.7/site-packages/django/core/files/storage.py", line 226, in location
    return os.path.abspath(self.base_location)
  File "/Users/a4923/.pyenv/versions/3.7.13/lib/python3.7/posixpath.py", line 378, in abspath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not function
```

</details>

**Comment by 4923** [comment]
---

## 우선 KeyError(None) 은 해결

```
$ python project/manage.py collectstatic --noinput
       Traceback (most recent call last):
         File "/tmp/build_9d8c9e6e/project/manage.py", line 22, in <module>
           main()
         File "/tmp/build_9d8c9e6e/project/manage.py", line 18, in main
           execute_from_command_line(sys.argv)
         File "/app/.heroku/python/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
           utility.execute()
         File "/app/.heroku/python/lib/python3.10/site-packages/django/core/management/__init__.py", line 413, in execute
           self.fetch_command(subcommand).run_from_argv(self.argv)
         File "/app/.heroku/python/lib/python3.10/site-packages/django/core/management/base.py", line 354, in run_from_argv
           self.execute(*args, **cmd_options)
         File "/app/.heroku/python/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
           output = self.handle(*args, **options)
         File "/app/.heroku/python/lib/python3.10/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 161, in handle
           if self.is_local_storage() and self.storage.location:
         File "/app/.heroku/python/lib/python3.10/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 215, in is_local_storage
           return isinstance(self.storage, FileSystemStorage)
         File "/app/.heroku/python/lib/python3.10/site-packages/django/utils/functional.py", line 246, in inner
           self._setup()
         File "/app/.heroku/python/lib/python3.10/site-packages/django/contrib/staticfiles/storage.py", line 438, in _setup
           self._wrapped = get_storage_class(settings.STATICFILES_STORAGE)()
         File "/app/.heroku/python/lib/python3.10/site-packages/django/core/files/storage.py", line 373, in get_storage_class
           return import_string(import_path or settings.DEFAULT_FILE_STORAGE)
         File "/app/.heroku/python/lib/python3.10/site-packages/django/utils/module_loading.py", line 17, in import_string
           module = import_module(module_path)
         File "/app/.heroku/python/lib/python3.10/importlib/__init__.py", line 126, in import_module
           return _bootstrap._gcd_import(name[level:], package, level)
```

런서버 안돌아가는 이유를 쫓아가면 뭐가 나올 것 같다.

**Comment by 4923** [comment]
```bash
 if self.is_local_storage() and self.storage.location:
         File "/app/.heroku/python/lib/python3.10/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 215, in is_local_storage
           return isinstance(self.storage, FileSystemStorage)
```

로컬저장소랑 뭔가 있는 것 같은데... -> whitespace (stroage 는 문제 없었고 문제생길만한 부분은 whitenoise 뿐이라 살펴본 결과 middleware에 잘못된 문구 추가함)
- [ref](https://stackoverflow.com/questions/31932023/receiving-error-django-core-exceptions-improperlyconfigured)

Solved!

**Comment by 4923** [comment]
> 여전히 해결되지 않는 스토리지 문제 무엇이 문제인가

```bash
-----> $ python project/manage.py collectstatic --noinput
       Traceback (most recent call last):
         File "/tmp/build_d0689806/project/manage.py", line 22, in <module>
           main()
         File "/tmp/build_d0689806/project/manage.py", line 18, in main
           execute_from_command_line(sys.argv)
         File "/app/.heroku/python/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
           utility.execute()
         File "/app/.heroku/python/lib/python3.10/site-packages/django/core/management/__init__.py", line 413, in execute
           self.fetch_command(subcommand).run_from_argv(self.argv)
         File "/app/.heroku/python/lib/python3.10/site-packages/django/core/management/base.py", line 354, in run_from_argv
           self.execute(*args, **cmd_options)
         File "/app/.heroku/python/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
           output = self.handle(*args, **options)
         File "/app/.heroku/python/lib/python3.10/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 161, in handle
           if self.is_local_storage() and self.storage.location:
         File "/app/.heroku/python/lib/python3.10/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 215, in is_local_storage
           return isinstance(self.storage, FileSystemStorage)
         File "/app/.heroku/python/lib/python3.10/site-packages/django/utils/functional.py", line 246, in inner
           self._setup()
         File "/app/.heroku/python/lib/python3.10/site-packages/django/contrib/staticfiles/storage.py", line 438, in _setup
           self._wrapped = get_storage_class(settings.STATICFILES_STORAGE)()
         File "/app/.heroku/python/lib/python3.10/site-packages/django/core/files/storage.py", line 373, in get_storage_class
           return import_string(import_path or settings.DEFAULT_FILE_STORAGE)
         File "/app/.heroku/python/lib/python3.10/site-packages/django/utils/module_loading.py", line 17, in import_string
           module = import_module(module_path)
         File "/app/.heroku/python/lib/python3.10/importlib/__init__.py", line 126, in import_module
           return _bootstrap._gcd_import(name[level:], package, level)
         File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
         File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
         File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
         File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
         File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
         File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
         File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
       ModuleNotFoundError: No module named 'whitenoise'
 !     Error while running '$ python project/manage.py collectstatic --noinput'.
       See traceback above for details.
       You may need to update application code to resolve this error.
       Or, you can disable collectstatic for this application:
          $ heroku config:set DISABLE_COLLECTSTATIC=1
       https://devcenter.heroku.com/articles/django-assets
 !     Push rejected, failed to compile Python app.
 !     Push failed
```

<details>
<summary>terminal log</summary>
<img width="665" alt="image" src="https://user-images.githubusercontent.com/60145951/172031133-7e1b6156-82dc-408f-853d-72b311450114.png">

### 추정 이유
<img width="1310" alt="image" src="https://user-images.githubusercontent.com/60145951/172031296-846913dc-f639-48e0-a630-ab066dc089dc.png">

[ref](https://freeman98.tistory.com/entry/웹서버에서-faviconico-관련-404-error-발생)

</details>
